### ISSUE TITLE
RuboCopの設定ファイル見直し

### ISSUE THREAD

**Issue by harutoreon** [harutoreon/surface-treatment-manager#251]
## 概要
.rubocop_todo.yml にすべての設定を押し込んでいたので、.rubocop.yml に移動する。
同時に設定ファイルの内容も見直しする。

## 学習内容
- [x] rubocop-performance の概要と使い方
- [x] rubocop-rails の概要と使い方
- [x] rubocop-rspec の概要と使い方

## 要件
- $ bundle exec rubocop を実行して警告が無いこと。
- テストがすべてパスすること。

## 実装
- [x] 設定ファイルの構造を決める
- [x] .rubocop_todo.yml の設定内容を .rubocop.yml に移動
- [x] 不要なコメントを削除
- [x] 見出しの追加
- [x] AllCopsの設定見直し
- [x] Copの断捨離や設定見直し
- [x] rubocop-performanceの導入
- [x] rubocop-railsの導入
- [x] rubocop-rspec の導入

## Pull request
- https://github.com/harutoreon/surface-treatment-manager/pull/267

## 参考情報
- [初学者のためのRuboCop](https://zenn.dev/isawa/articles/ad0da7acdc276a)
- [linyows/.rubocop.yml](https://gist.github.com/linyows/ace586b118f87291ed3e)
- [Ruby on Rails (7.0) の実践的な開発手法に触れてみよう - 2-2. Rubocop](https://zenn.dev/tmasuyama1114/books/ab51fea5d5f659/viewer/rubocop)
- [【Rails】RuboCopの導入 ~ おすすめルールの設定方法](https://blog.to-ko-s.com/rubocop-setting/)
- [Linyclar - RuboCopメモ](https://linyclar.github.io/rails_memos/development_tools/rubocop/)
- [.rubocop.ymlシンプルに、ゆるめにやりたいんじゃ](https://hoshinotsuyoshi.com/post/rubocop_yaml/)

**Comment by harutoreon** [comment]
見直し対象の Cop
```yaml
Layout/LineLength:  # ソースコードのリファクタリングで対応を検討
  Max: 198

Layout/IndentationWidth:  # 無効化を検討
  Exclude:
    - 'app/controllers/**/*'
    - 'app/models/**/*'
    - 'app/uploaders/**/*'

```
